version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: subscription-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: telix099
      MYSQL_DATABASE: subscription_automation
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local 